name: example
description: "Open UI is a sandbox application that demonstrates the power of an Empathetech UI. If you like Open UI, checkout https://github.com/Empathetech-LLC/empathetech_flutter_ui"
version: 2.3.2+34
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter (Google)
  go_router: ^14.8.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3

  # Community
  email_validator: ^3.0.0
  feedback: ^3.2.0
  file_picker: ^10.3.6
  file_saver: ^0.2.14
  flutter_localized_locales: ^2.0.5
  flutter_platform_widgets: ^9.0.0
  go_transitions: ^0.8.3
  line_icons: ^2.0.3
  xml: ^6.6.1

  empathetech_flutter_ui:
    path: ../
  efui_bios:
    path: ../../efui_bios

dev_dependencies:
  dependency_validator: ^5.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/settings-sandbox.jpg
    - assets/images/settings-sandbox-round.png

flutter_launcher_icons:
  image_path: assets/images/settings-sandbox.jpg
  adaptive_icon_foreground: assets/images/settings-sandbox-round.png
  adaptive_icon_background: "#F5F5F5"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/images/settings-sandbox.jpg
  android: true
  ios: true
  web: true
