name: empathetech_flutter_ui
description: "Build apps for anyone. EFUI makes building truly accessible apps Ez. So anyone can enjoy your great idea!"
version: 11.0.0
repository: https://github.com/Empathetech-LLC/empathetech_flutter_ui

environment:
   sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # Flutter (Google)
  google_fonts: ^8.0.1
  go_router: ^14.8.1
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  video_player: ^2.10.1
  web: ^1.1.1
  
  # Community
  country_flags: ^4.1.2
  extended_image: ^10.0.1
  file_picker: 10.3.8
  file_saver: ^0.2.14
  flex_color_picker: ^3.8.0
  flutter_localized_locales: ^2.0.5
  image: ^4.7.2
  line_icons: ^2.0.3
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  
dev_dependencies:
  ## For development
  dartdoc: ^9.0.2
  dependency_validator: ^5.0.4
  flutter_lints: ^6.0.0

  ## For example app (Open UI)
  # Local
  example:
    path: example
  efui_bios:
    path: ../efui_bios
  
  # Community
  email_validator: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  xml: ^6.6.1

flutter:
  generate: true

  assets:
    - assets/
    - assets/nebula-jeremy-m√ºller.jpg